### ISSUE TITLE
HTML output with -o flag doesn't create files in expected folder

### ISSUE THREAD

**Issue by tobilg** [mhlabs/cfn-diagram#10]
When trying to generate the HTML docs via specifying the output folder:

```bash
$ cfn-dia html -t .serverless/cloudformation-template-update-stack.json -o docs/stack/index.html
```
It return no error, but the output is not generated unfortunately. When omitting the -o flag, the output is generated in the default /tmp folder.

**Comment by ljacobsson** [comment]
Thanks for taking time to report :-)

This is now fixed in v1.1.3
