### ISSUE TITLE
Support for EventBridge to Lambda with SAM

### ISSUE THREAD

**Issue by nmoutschen** [mhlabs/cfn-diagram#13]
Hey!

I'm using SAM in [this project](https://github.com/aws-samples/aws-serverless-ecommerce-platform), which uses EventBridge quite heavily. However, when I generated a diagram for [the payment service](https://github.com/aws-samples/aws-serverless-ecommerce-platform/blob/master/payment/template.yaml), I noticed that I don't see connections between EventBridge and the Lambda functions. This is without any filtering by the way.

Event though the event bus is defined in another stack, it'd be nice to have a view of what invoke those Lambda functions, similar to how you have it with API Gateway.

![payment-template](https://user-images.githubusercontent.com/15308855/101325696-7970ef80-386c-11eb-8112-4690a79e2174.png)

**Comment by ljacobsson** [comment]
Thanks for reporting!

Likewise - we're using lots of EventBridge and I agree this is needed.

**Comment by ljacobsson** [comment]
This is fixed in v1.1.25

I'm not always that fast :-)
