### ISSUE TITLE
Visualize multiple Templates 

### ISSUE THREAD

**Issue by K-Stefan** [mhlabs/cfn-diagram#19]
Cloud Formation Templates are depending often on each other. CFN Export/Import are used to re-use resources like a VPC. 

It would be cool to create a holistic view of multiple CFN templates with `cfn-dia`!

Additional resources/info: 
Maybe the AWS rain tool can help to create a tree of the dependencies. See command "rain tree"  - https://github.com/aws-cloudformation/rain

**Comment by ljacobsson** [comment]
Thanks for this request! 

Currently you can only go as far as rendering nested stacks that exist on your local workspace. 

However, in the last release (v1.1.11) we introduced fetching deployed templates using the AWS SDK. This, of course opens up new possibilities of doing what you're saying.

The risk is that the output will be extremely cluttered depending on the dependency graph. Maybe it'd be a good compromise to make dependent stacks navigatable icons. I.e they appear in the diagram as a CloudFormation icon, but when clicked it'll open up and expand the diagram with that stack. This would probably not work well with the draw.io output.

Ps. thanks for pointing me at `rain`. It's new to me and looks interesting :+1:

**Comment by wichert** [comment]
A related use case for me would be to visualise the output of [CDK](https://aws.amazon.com/cdk/), which is a set of CloudFormation files, along tree.json file that specifies how they are linked together.

**Comment by ljacobsson** [comment]
@wichert thanks for this! I've opened #20 to address this

**Comment by ljacobsson** [comment]
I've just released v1.1.13 which has CDK support.

This should also handle `Fn::ImportValue` and reference the dependent stack.

For CDK this works since the export name tells us which stack made the export. 

For SAM or vanilla CloudFormation this is a more difficult task.

If you get a chance, please have a go at v1.1.13. I'm new to CDK, so might have missed a thing or two.

Will leave this issue open for discussion

**Comment by ljacobsson** [comment]
Closing this in favour of #25. Enhancement is made - now on to thee bugs :-)

**Comment by collindutter** [comment]
@ljacobsson I'm having some difficulty rendering my nested stacks in a SAM application. The nested stacks are modeled as [SAM Nested Applications](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-nested-applications.html) in the main template. Is this a supported use-case?

Thanks!
