### ISSUE TITLE
Allow using existing `cdk.out`

### ISSUE THREAD

**Issue by wichert** [mhlabs/cfn-diagram#23]
We use Python for CDK, and require some extra magic to handle AWS authentication. The end result of that is that to run CDK the real command I need to use is this: `aws-woven-auth dev run poetry run cdk synth --all`. This is of course highly specific to our environment, so cfn-diagram does not need to support that directly. What we do need to make the CDK integration work for us is an ability to either use an existing `cdk.out` directory, or be able to specify our own cdk command.

**Comment by ljacobsson** [comment]
Thanks for reporting this @wichert 

This use case makes sense. There was already an option for overriding the default `cdk.out` path (`--cdk-output|-co`)

However, using that did a `cdk-synth` in its place.

Based on other feedback I've had, I've now added an option to skip the synth step (`--skip-synth|-s`).

This lets you do something like
`aws-woven-auth dev run poetry run cdk synth --all && cfn-dia HTML --skip-synth --cdk-output ./your-existing-dir`

Will release this shortly

**Comment by ljacobsson** [comment]
This has been released in v 1.1.15.

Please reopen if the issue persist

**Comment by wichert** [comment]
I'm not sure this works correctly. I have a `cdk.out` folder with 10 cfn templates in it. When I run `npx @mhlabs/cfn-diagram@1.1.15 html -s -co cdk.out` I only see the output from a single cfn template, instead of all templates.
