### ISSUE TITLE
CDK Multi-Stack app fails with TypeError: Cannot read property 'Outputs' of undefined

### ISSUE THREAD

**Issue by michaelfecher** [mhlabs/cfn-diagram#25]
I have a CDK multi-stack application, which I'd like to visualize.
It's compilable and synthesizes as well.
Running the command like proposed in the README:

```
cfn-dia html
```

Output:
```
Successfully synthesized to /cdk.out
Supply a stack id LIST_OF_STACKS to display its template.
TypeError: Cannot read property 'Outputs' of undefined
    at findAllValues (/home/mf/.nvm/versions/node/v12.20.1/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:89:60)
    at findAllValues (/home/mf/.nvm/versions/node/v12.20.1/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:123:7)
    at /home/mf/.nvm/versions/node/v12.20.1/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:120:9
    at Array.forEach (<anonymous>)
    at findAllValues (/home/mf/.nvm/versions/node/v12.20.1/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:119:17)
    at findAllValues (/home/mf/.nvm/versions/node/v12.20.1/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:123:7)
    at findAllValues (/home/mf/.nvm/versions/node/v12.20.1/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:123:7)
    at findAllValues (/home/mf/.nvm/versions/node/v12.20.1/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:123:7)
    at findAllValues (/home/mf/.nvm/versions/node/v12.20.1/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:123:7)
    at findAllValues (/home/mf/.nvm/versions/node/v12.20.1/lib/node_modules/@mhlabs/cfn-diagram/resources/JsonUtil.js:123:7)
```

**Comment by ljacobsson** [comment]
Hi!

Thanks for reporting this. Would it be possible to point me at a CDK project through which I can reproduce this?

Thanks :-)

**Comment by michaelfecher** [comment]
Hey,
thanks for your reply.
Unfortunately, it's a client's project, where I thought to give a shot for cfn-dia. :)
There's a static stack for imported VPCs, Route53 DNS Entries, Security Groups, etc...
However, I'm not sure if this could be one issue for the cfn-dia.
Also, I'm not sure how I can provide a minimal example to make it happen... :/
I didn't see a debug or verbose flag in cfn-dia.
Any other chance I can provide you more information to help you through this?

**Comment by giampaolotrapasso** [comment]
I have the same problem and unfortunately, at the moment, I can't share the template I'm working on. What about having a "verbose" mode that would help to identify problems without sharing the template?

**Comment by VadimKraus** [comment]
I'm having the same issue. The problem is probably related to how the stacks are nested.

The lookup in the following lines cause the template cache to not contain the nested stacks:
https://github.com/mhlabs/cfn-diagram/blob/2b2e650beea341192aa6af26d808786897d3e978/shared/templateParser.js#L60

In my use case, the `tree.json` file contains a stack and in its children there are additional Stacks and NestedStacks defined. 
However, the stack ids are not referenced there directly.  Here is an example:

```json
"Tree": {[...]}
"MainStack": {
"children": {
 "ChildStack": {
            "id": "ChildStack",
             [...]
            "constructInfo": {
              "fqn": "@aws-cdk/core.Stack",
              "version": "1.93.0"
            }
}
```
Running `cdk synth MainStack` results in an output like this:

```
assets...
MainStack.template.json
MainStackChildStackC60DDEAF.template.json
```

I modified the lines mentioned above manually to contain the child `stacks.push("MainStackChildStackC60DDEAF")` then the error disappeared.

A workaround might be to allow multiple templates using the `-t` cli parameter?

**Comment by rehanvdm** [comment]
Same problem.. Using the CDK option `-co` works but then it uses ALL the stacks. Having 12 stacks all display their resources on 1 image is not worth much. I second making -t accept multiple stacks and/or if that stack output is not found in the others to not error like it is doing now. 

Also let it generate all 12 stacks but create all of them in their own "bounding" box. That would actually be a huge win!

**Comment by RajasGujarathi** [comment]
Facing the same issue ...

![image](https://user-images.githubusercontent.com/31616516/118224756-10794d80-b484-11eb-8436-f1cf87c2cf14.png)

**Comment by ljacobsson** [comment]
Thanks for all the input!

Just want to let you now that addressing this is high up on my OSS prio list.

I think I agree with allowing multiple stacks after the `-t` parameter.

Must admit that I'm (still) writing my templates in SAM and am not very experienced with CDK, but I should be able to reproduce and come up with a fix.

**Comment by ljacobsson** [comment]
I've been searching the internet for CDK multi stack setups through which I can reproduce the problem, but I'm struggling.

I found [this](https://github.com/apptension/aws-boilerplate) repo of a fairly complex CDK stack, but when I run `cfn-dia html` on it it renders according to the current design - the root template visible and child templates hidden by default.

I'm not sure what I'm missing, but I guess it's got to do with a certain way of making exports between stacks.

Would be very helpful if anyone can point me at a reproducible stack.

**Comment by VadimKraus** [comment]
Good luck :D

https://github.com/VadimKraus/cfn-diagram-issue-25

**Comment by ljacobsson** [comment]
@VadimKraus thank you so much for the example project! It really helped me!

I've just pushed out v1.1.26.

It's passed all my testing, but I'll leave this issue open until you can verify it works on your end.

In response to the multiple template `-t`-parameter - I added a `--stacks` parameter where you can pass a comma separated list of stack names

**Comment by VadimKraus** [comment]
Looks good, thanks.
