### ISSUE TITLE
HTML output does not render proper titles

### ISSUE THREAD

**Issue by mbonig** [mhlabs/cfn-diagram#30]
When rendering to HTML the title gets set to a `pre` formatted JSON (or yaml) representation. However, the title property doesn't render spaces properly.

![image](https://user-images.githubusercontent.com/1559437/110148923-a618a280-7d9a-11eb-844a-8f0ba793dc76.png)

Looking at the rendered HTML, it appears that vis.js might be trying to replace newlines with `br`s causing this misformatting:

![image](https://user-images.githubusercontent.com/1559437/110149101-e11ad600-7d9a-11eb-9c28-05ca3cabef94.png)

**Comment by ljacobsson** [comment]
Hey @mbonig 

Thanks for reporting. I've noticed the same thing and this used to work, but suddenly isn't. I have the feeling it's happened through some update of the visjs lib. Been searching their github issues without any luck.

I'll raise an issue there and link to this one

**Comment by mbonig** [comment]
Is there a way to control what the title renders to? I'd love to replace it with a link to the resource in AWS.

**Comment by ljacobsson** [comment]
I like the idea a lot and I would also want this, but since the AWS console doesn't follow any conventions, there'd be custom logic per resource to build the URL

I've attempted this in [another project](https://github.com/mhlabs/cfn-resource-actions), but it just gets too time consuming

**Comment by ljacobsson** [comment]
Version 1.1.20 that just got deployed fixes the formatting issue :+1: 

Will close this issue and will address the linking to the console if I find a straight forward ARN -> URL mapping.

Thanks again for reporting
