### ISSUE TITLE
How do you get out of the cfn-dia menu?

### ISSUE THREAD

**Issue by john-aws** [mhlabs/cfn-diagram#32]
Installed on Mac, I ran `cfn-dia draw.io -t template.yml`. That presented me with the following text-based configuration menu:

```
Diagram will be written to template.drawio
Press CTRL+C to exit
? Options (Use arrow keys)
❯ Filter resources by type
  Filter resources by name
  Edge labels: On
```

Hitting Enter navigates into an option where you can make changes, but there is no clear way to actually tell cfn-dia "OK, now do it". No combination of keypresses seems to get you out of the menu and tell cfn-dia to actually diagram the supplied template. You are stuck in the menu.

I resorted to reading your [package.json](https://github.com/mhlabs/cfn-diagram/blob/master/package.json) and see that you are using the [inquirer](https://www.npmjs.com/package/inquirer) NPM package but their documentation didn't provide any clue either.

How do you get out of the menu (other than to hit ctrl+c and exit)?

**Comment by john-aws** [comment]
Oh wow. I've just realized that if you hit ctrl+c to exit, it will actually write out the template.drawio file. Unbelievable.

**Comment by ljacobsson** [comment]
Hi @john-aws,

Thanks for your feedback - I agree it's unintuitve to use the kill process command to exit the app.

The way it's set up is that the template.drawio file is created upon launch with everything visible by default. Each time you toggle any filters it'll rewrite the file, Nothing actually gets written when you hit ctrl+c.

The idea is that you keep the diagram open in vscode with [this extension](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio) installed whilst you tweak the filters. 

How about the following actions?
1. I add an 'Exit' option from the menu
2. Hitting exit will prompt you if you want to keep the diagram or not

**Comment by john-aws** [comment]
Thanks for the quick response. The explanation makes sense and I think your proposed changes would be very helpful, thank you.

In my short experience with the Draw.io VS Code plugin, it doesn't reliably refresh the diagram when you make changes using cfn-dia. It typically works first time I make cfn-dia changes but not thereafter. The underlying template.drawio file *is* being updated each time and the drawio template size is changing but the VS Code plugin is not detecting that change (or not refreshing the diagram, after the first refresh). I'll take that up with the plug-in author.

**Comment by ljacobsson** [comment]
This enhancement will be released shortly.

I've experienced what you describe with the diagram not updating, but not very often (am on linux). I've seen it for other file types as well that's been modified by another process, so I wonder if it's a vscode thing
