### ISSUE TITLE
cfn-dia-image not working

### ISSUE THREAD

**Issue by Jordhan-Carvalho** [mhlabs/cfn-diagram#37]
Not sure if I'm missing something, but after installing the @mhlabs/cfn-diagram-ci the cfn-dia image command still not working
`error: unknown command 'image'. See 'cfn-dia --help'.`

**Comment by ljacobsson** [comment]
Thanks for this!

I've updated `cfn-diagram-ci` and [the readme](https://github.com/mhlabs/cfn-diagram#ci-mode) to address this
