### ISSUE TITLE
Could not find vscode

### ISSUE THREAD

**Issue by 206687668** [mhlabs/cfn-diagram#45]
Every time I try to create a new draw.io file I get the error 'Could not find vscode' and 'Not a diagram file' and 'Cannot read property 'getAttribute of Null'.

**Comment by ljacobsson** [comment]
Hi,

Thanks for reporting. This is a new one.

The draw.io visualisation is expecting you to use with the [draw.io extension for vscode](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio).

The readme could be clearer on that.

To me it looks like you don't have vscode in your path. Which OS are you using?

**Comment by 206687668** [comment]
You're right, vscode wasn't in my path, corrected it and fixed the issue. Thank you!

**Comment by ljacobsson** [comment]
Great! :tada:
