### ISSUE TITLE
Ability to put data.js directly in index.html

### ISSUE THREAD

**Issue by robbrad** [mhlabs/cfn-diagram#70]
We are looking to include the index.html directly in a Confluence site

To do this we have to ref the page the index.html and data.js is attached to - so to save having to hack around with refs to the data.js it would be good to have the data.js content self contained in the index.html - no seperate file

https://github.com/mhlabs/cfn-diagram/blob/224da782f551100c0a32e802ef46a6079f06e520/graph/Vis.js#L205

eg.

<script type="text/javascript">
  data.js CONTENT
</script>

**Comment by ljacobsson** [comment]
Thanks for this @robbrad!

Maybe this should even be the default behaviour
